---
- name: RESTORE CONFIGURATION
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: COPY RUNNING CONFIG TO ROUTER
      net_put:
        src: ./backup/{{inventory_hostname}}.config
        dest: flash:/{{inventory_hostname}}.config
      vars:
        ansible_command_timeout: 120

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
